# Generated by Django 3.0.6 on 2020-05-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytwitter', '0002_auto_20200510_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='mention_to_other_tweet',
            field=models.OneToOneField(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='mytwitter.Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='retweeted_tweet_id',
            field=models.CharField(default='-1', max_length=20),
        ),
    ]
