# Generated by Django 3.0.6 on 2020-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytwitter', '0003_auto_20200511_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='mention_to_other_tweet',
            field=models.CharField(default='-1', max_length=20),
        ),
    ]
